site_name: Mongoose文档
site_description: Mongodb NodeJs 组件中文文档
site_author: Nosy
copyright: "版权 &copy; 2022 -  wdk-docs.github.io"

repo_name: wdk-docs/mongoose-docs
repo_url: https://github.com/wdk-docs/mongoose-docs
edit_uri: ""

docs_dir: source
site_dir: docs

theme:
  name: material

  include_search_page: false
  search_index_only: true

  language: zh
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  # logo:
  # icon: "\uE80C"
  icon:
    logo: material/library
  # extra_css: [assets/stylesheets/extra.css]
extra:
  social:
    - icon: fontawesome/brands/github
      link: http://wdk-docs.github.io
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wdk-docs
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wdk-docs
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/wdk-docs

markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - 前言: index.md
  - 快速开始: QuickStart.md
  - 连接:
      - 连接手册: connection/guide.md
      - 连接API: connection/api.md
  - 模式:
      - 模式手册: schema/guide.md
      - 模式API: schema/api.md
      - 模式类型API: schema/type.md
  - 模型:
      - 模型手册: model/guide.md
      - 模型API: model/api.md
  - 文档:
      - 文档手册: document/guide.md
      - 文档API: document/api.md
  - 查询:
      - 查询手册: query/guide.md
      - 查询API: query/api.md
  - 其它手册:
      - 验证: guide/Validation.md
      - 中间件: guide/Middleware.md
      - 填充: guide/Populate.md
      - 鉴别器: guide/Discriminators.md
      - 插件: guide/Plugins.md
  - 其它API:
      - 聚合: api/Aggregate.md
      - 虚拟类型: api/VirtualType.md
      - 错误: api/Error.md
  - 升级到5: migrating_to_5.md
  - 版本兼容性: VersionCompatibility.md
  - 常问问题: FAQ.md
  - 驱动:
      - unified-topology: MongoDB_NodeJS_Driver/unified-topology.md
